# Netlify Configuration

[build]
  command = "npm run build"
  publish = "out"

# Handle CORS and proper headers for videos
[[headers]]
  for = "*.mp4"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "video/mp4"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.webm"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "video/webm"
    Cache-Control = "public, max-age=31536000"

# Force client-side rendering for pages with video content
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs" 